#!/bin/bash
set -e

echo "🚀 Setting up enhanced Norn features..."

# 1. Check Rust version
echo "Checking Rust version..."
rustc --version

# 2. Install dependencies
echo "Installing dependencies..."
if ! command -v cargo-criterion &> /dev/null; then
    echo "Installing cargo-criterion..."
    cargo install cargo-criterion
fi

if ! command -v cargo-audit &> /dev/null; then
    echo "Installing cargo-audit..."
    cargo install cargo-audit
fi

# 3. Build with enhanced features
echo "Building with enhanced features..."
cargo build --workspace --features production --release

# 4. Run tests
echo "Running tests..."
cargo test --workspace --features production --all-features

# 5. Create config directory
echo "Creating configuration..."
mkdir -p config

cat > config/enhanced.toml <<EOF
# Enhanced Norn Node Configuration
# Generated by scripts/setup_enhanced.sh

[network]
listen_address = "/ip4/0.0.0.0/tcp/4001"
mdns = true

[txpool]
enabled = true
max_size = 20480
replacement_enabled = true
min_fee_increase_bps = 1000
expiration_seconds = 3600
cleanup_interval = 300

[sync]
mode = "fast"
header_batch_size = 500
body_batch_size = 100
checkpoint_interval = 1000
max_parallel_downloads = 10
request_timeout_secs = 30

[monitoring]
enabled = true
metrics_port = 9090
EOF

echo "✅ Setup complete!"
echo "📝 Configuration saved to config/enhanced.toml"
echo ""
echo "To start a node with enhanced features:"
echo "  ./scripts/start_enhanced_node.sh"
